import { test, expect } from "@playwright/test";
test("job wizard validates, displays currency and prevents resubmission after success", async ({page}) => {
 let saves=0;
 await page.route("**/rest/v1/job_submissions", async route => { saves++; await route.fulfill({status:201,body:""}); });
 await page.goto("/post-a-job");
 await page.getByRole("button",{name:"Next: Salary details"}).click();
 await expect(page.locator(".wizard-error-summary")).toBeVisible();
 await page.locator('[name=title]').fill("Test engineer");
 await page.locator('[name=company_name]').fill("Test company");
 await page.locator('[name=location]').fill("Lagos");
 await page.getByRole("button",{name:"Next: Salary details"}).click();
 await page.getByLabel("Salary currency").selectOption("USD");
 await page.locator('[name=salary_min]').fill("2000");
 await page.locator('[name=salary_max]').fill("1000");
 await page.getByRole("button",{name:"Next: Application details"}).click();
 await expect(page.locator('#salary_max-error')).toBeVisible();
 await page.locator('[name=salary_min]').fill("500");
 await page.getByRole("button",{name:"Next: Application details"}).click();
 await expect(page.locator('[data-step="3"]')).toBeVisible();
 await page.getByRole("button",{name:"Back",exact:true}).click();
 await expect(page.locator('.salary-preview')).toContainText("US$");
 await page.getByRole("button",{name:"Next: Application details"}).click();
 const future=new Date();future.setDate(future.getDate()+14);
 await page.locator('[name=expires_at]').fill(future.toISOString().slice(0,10));
 await page.locator('[name=application_url]').fill("https://example.com/job");
 await page.locator('[name=contact_email]').fill("test@example.com");
 await page.locator('textarea[name=description]').fill("Test job description. ".repeat(8));
 await page.locator('[name=no_candidate_fees_confirmed]').check();
 await page.getByRole("button",{name:"Submit job for review"}).click();
 await expect(page.getByRole("heading",{name:"Job submitted for review"})).toBeVisible();
 await expect(page.getByRole("button",{name:"Submit job for review"})).toHaveCount(0);
 expect(saves).toBe(1);
});
