create table if not exists public.early_access_signups (
  id bigint generated by default as identity primary key,
  email text not null unique check (length(email) between 5 and 254),
  source text not null default 'homepage',
  consented_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.early_access_signups enable row level security;

create policy "allow anonymous early-access signup"
on public.early_access_signups
for insert
to anon
with check (
  source = 'homepage'
  and length(email) between 5 and 254
  and email = lower(email)
);

grant insert (email, source, consented_at)
on public.early_access_signups to anon;

create table if not exists public.analytics_daily (
  event_date date not null,
  event_name text not null check (
    event_name in (
      'page_view',
      'paye_calculated',
      'pdf_exported',
      'excel_exported',
      'print_opened'
    )
  ),
  page_path text not null,
  referrer_host text not null,
  event_count bigint not null default 0 check (event_count >= 0),
  primary key (event_date, event_name, page_path, referrer_host)
);

alter table public.analytics_daily enable row level security;

create or replace function public.record_analytics_event(
  event_name text,
  page_path text,
  referrer_host text
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if event_name not in (
    'page_view',
    'paye_calculated',
    'pdf_exported',
    'excel_exported',
    'print_opened'
  ) then
    return;
  end if;

  insert into public.analytics_daily (
    event_date,
    event_name,
    page_path,
    referrer_host,
    event_count
  )
  values (
    current_date,
    event_name,
    left(page_path, 160),
    left(referrer_host, 120),
    1
  )
  on conflict (event_date, event_name, page_path, referrer_host)
  do update set event_count = analytics_daily.event_count + 1;
end;
$$;

revoke all on function public.record_analytics_event(text, text, text)
from public, anon, authenticated;

grant execute on function public.record_analytics_event(text, text, text)
to anon;
